services:
  # docker exec -it debian-xfce4-desktop-1 passwd debian
  # podman exec -it debian-xfce4_desktop_1 passwd debian
  desktop:
    image: docker.io/meteor1113/debian-xfce4
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: always
    ports:
      - "5022:22"
      - "5389:3389"
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /:/mnt/host
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    #   - /run:/run:rw
    #   - /tmp:/tmp
    # tmpfs:
    #   - /run
    #   - /run/lock
    #   - /tmp
