services:
  # wechat installed by Dockerfile cannot use, maybe it needs bwrap/apparmor?
  # docker exec -it deepin-desktop-xfce4-1 bash -c "apt update && apt install -y store.spark-app.wechat-linux-spark"
  # docker exec -it deepin-desktop-xfce4-1 passwd deepin
  xfce4:
    image: docker.io/meteor1113/deepin-xfce4
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: always
    ports:
      - "4022:22"
      - "4389:3389"
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /:/mnt/host
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    #   - /run:/run:rw
    #   - /tmp:/tmp
    # tmpfs:
    #   - /run
    #   - /run/lock
    #   - /tmp
