services:
  # docker exec -it ubuntu-desktop-xfce4-1 passwd ubuntu
  xfce4:
    image: meteor1113/ubuntu-xfce4
    restart: unless-stopped
    ports:
      - "2422:22"
      - "3489:3389"
    privileged: true
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    #   - /run:/run:rw
    #   - /tmp:/tmp
    # tmpfs:
    #   - /run
    #   - /run/lock
    #   - /tmp
