name: deepin-xfce4

on:
  push:
    branches: [ "main" ]
    paths:
      - "deepin-xfce4/**"
      - ".github/workflows/deepin-xfce4.yml"
      - ".github/workflows/deploy_docker_hub.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "deepin-xfce4/**"
      - ".github/workflows/deepin-xfce4.yml"
      - ".github/workflows/deploy_docker_hub.yml"

jobs:
  deploy:
    uses: ./.github/workflows/deploy_docker_hub.yml # meteor1113/dockerfiles/.github/workflows/deploy_docker_hub.yml@main
    with:
      context: "{{defaultContext}}:deepin-xfce4"
      # platforms: "linux/amd64"
      images: "meteor1113/deepin-xfce4"
      tags: |
        type=raw,value=latest
        type=raw,value=23
    secrets:
      username: "${{ secrets.DOCKERHUB_USERNAME }}"
      token: "${{ secrets.DOCKERHUB_TOKEN }}"
