name: ubuntu-xfce4

on:
  push:
    branches: [ "main" ]
    paths:
      - "ubuntu-xfce4/**"
      - ".github/workflows/ubuntu-xfce4.yml"
      - ".github/workflows/deploy_docker_hub.yml"
    paths-ignore:
      - "ubuntu-xfce4/.dockerignore"
      - "ubuntu-xfce4/docker-compose.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "ubuntu-xfce4/**"
      - ".github/workflows/ubuntu-xfce4.yml"
      - ".github/workflows/deploy_docker_hub.yml"
    paths-ignore:
      - "ubuntu-xfce4/.dockerignore"
      - "ubuntu-xfce4/docker-compose.yml"

jobs:
  deploy:
    uses: ./.github/workflows/deploy_docker_hub.yml # meteor1113/dockerfiles/.github/workflows/deploy_docker_hub.yml@main
    with:
      context: "{{defaultContext}}:ubuntu-xfce4"
      # platforms: "linux/amd64"
      images: "meteor1113/ubuntu-xfce4"
      tags: |
        type=raw,value=latest
        type=raw,value=24.04
    secrets:
      username: "${{ secrets.DOCKERHUB_USERNAME }}"
      token: "${{ secrets.DOCKERHUB_TOKEN }}"
