name: ubuntu-xfce4

on:
  push:
    branches: [ "main" ]
    paths:
      - "ubuntu-xfce4/**"
      - ".github/workflows/ubuntu-xfce4.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "ubuntu-xfce4/**"
      - ".github/workflows/ubuntu-xfce4.yml"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:ubuntu-xfce4"
          push: true
          tags: |
            meteor1113/ubuntu-xfce4:24.04
            meteor1113/ubuntu-xfce4:latest
